name: Update JSON Files

on:
    repository_dispatch:
        types: [update-data]
    schedule:
        - cron: "*/60 * * * *"

jobs:
    data:
        name: update-data
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2
            - name: Setup php
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "7.2"
                  extensions: curl, json
            - name: Update composer
              run: |
                  composer update
            - name: Install dependencies
              run: |
                  composer install
            - name: Run Script
              run: |
                  php convert.php
            - name: Update data
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./data
                  publish_branch: gh-pages
            - name: Notification Slack
              uses: 8398a7/action-slack@v2
              with:
                  status: ${{ job.status }}
              env:
                  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
              if: always()
